package net.avalon.gulimall.product.mapper.generator;

import java.util.List;
import net.avalon.gulimall.product.mapper.generator.po.AttrGroupPo;
import net.avalon.gulimall.product.mapper.generator.po.AttrGroupPoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AttrGroupPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    long countByExample(AttrGroupPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    int deleteByExample(AttrGroupPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long attrGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    int insert(AttrGroupPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    int insertSelective(AttrGroupPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    List<AttrGroupPo> selectByExample(AttrGroupPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    AttrGroupPo selectByPrimaryKey(Long attrGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") AttrGroupPo row, @Param("example") AttrGroupPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") AttrGroupPo row, @Param("example") AttrGroupPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AttrGroupPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AttrGroupPo row);
}